# Generated by Django 3.2.12 on 2022-04-14 03:05

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0006_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 4, 16, 3, 5, 1, 29575, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
