# Generated by Django 3.2.12 on 2022-04-25 01:53

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0008_create_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 4, 27, 1, 53, 55, 138572, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
