# Generated by Django 3.2.12 on 2022-04-25 02:42

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0009_alter_shopuser_activation_key_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 4, 27, 2, 42, 1, 570019, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
